# MÉTODO THE WAY OF THE MASTER

TODO: Prepare a little cheatsheet with WDJD + CCRAFT
TODO: Pensar numa organização de analogia + verso unificada

O método The Way of the Master e um método baseado na Bíblia para evangelizar.

Esta baseado em duas partes a primeira parte consiste em falar na consciência de
forma que a pessoa este consciente que transgrediu a lei de Deus e por esse
motivo caiu em pecado. A segunda parte consiste em uma vez que a pessoa entende
sua transgressão, então dar a boa noticia do evangelho de Jesus.

Esse método faz sentido pois se fizermos uma analogia com uma doença, o paciente
primeiro deve receber a má noticia que esta doente para então aceitar o
tratamento, se não souber da doença, então vai achar que não precisa tratamento
e ate pode lhe parecer ofensivo. Isto também e baseado num principio Bíblico.

## Primeira parte. A lei (`BMJD`)

Essa parte começa normalmente com a pergunta `vc se considera uma boa pessoa?`.
Quando a pessoa responde afirmativamente então o evangelista vai `levar
sistematicamente pela lei` (se tem mentido, roubado, etc). Depois se `sumarizam as
admissões` da pessoa e se `pergunta se a condenação eterna e importante` para a
pessoa. Finalmente, una vez a pessoa esta consciente que não e livre de pecado e
do destino que lhe aguarda então e dada a `solução: arrependimento e fé em Jesus`.

Esse procedimento esta baseado nas escrituras, especificamente em
[Romanos 3:19][pt-rom-3:19]-20 diz:
[pt-rom-3:19]: bible://jfa-rc/Romans+3:19

> Ora, nós sabemos que tudo o que a lei diz aos que estão debaixo da lei, o diz,
> para que toda a boca esteja fechada e todo o mundo seja condenável diante de
> Deus. Por isso nenhuma carne será justificada diante dele pelas obras da lei,
> porque pela lei vem o conhecimento do pecado.

[Gálatas 3:24][pt-gal-3:24]-25 diz:
[pt-gal-3:24]: bible://jfa-rc/Galatians+3:24

> De maneira que a lei nos serviu de aio, para nos conduzir a Cristo, para que
> pela fé fôssemos justificados. Mas, depois que a fé veio, já não estamos
> debaixo de aio.

[Salmos 19:7][pt-psalm-19:7] também proclama:
[pt-psalm-19:7]: bible://jfa-rc/Psalms+19:7

> A lei do SENHOR é perfeita e refrigera a alma; o testemunho do SENHOR é fiel e
> dá sabedoria aos símplices.

Concluímos então que o método possui fundamento bíblico quando uma pessoa se
olha no espelho da lei de Deus, e reconhece o seu pecado então esta pronta para
o Evangelho e entender a santidade, justiça e perfeição de Deus, e a salvação
pelo sacrifico de Jesus Cristo. Como Paulo escreve em [Romanos 3:21][pt-rom-3:21-26]-26,
[pt-rom-3:21-26]: bible://jfa-rc/Romans+3:21

> Mas agora se manifestou sem lei a justiça de Deus, tendo o testemunho da lei e
> dos profetas; Isto é, a justiça de Deus pela fé em Jesus Cristo para todos e
> sobre todos os que crêem; porque não há diferença. Porque todos pecaram e
> destituídos estão da glória de Deus. Sendo justificados gratuitamente pela sua
> graça, pela redenção que há em Cristo Jesus, Ao qual Deus propôs para
> propiciação pela fé no seu sangue, para demonstrar a sua justiça pela remissão
> dos pecados dantes cometidos, sob a paciência de Deus; Para demonstração da
> sua justiça neste tempo presente, para que ele seja justo e justificador
> daquele que tem fé em Jesus.


### `B`: Vc se considera uma `BOA` pessoa?

Pergunta:

Essa fase e apenas fazer essa pergunta: `vc se considera uma boa pessoa?`

Versículos de referencia:

A pessoa provavelmente vai falar que sim como diz [Provérbios 20:6][pt-prov-20:6],
[pt-prov-20:6]: bible://jfa-rc/Proverbs+20:6

> Cada qual entre os homens apregoa a sua bondade; mas o homem fiel, quem o achará? (jfa-rc)

Mas sabemos que ninguém e bom, mas só Deus como Jesus disse em
[Lucas 18:19][pt-luke-18:19]:
[pt-luke-18:19]: bible://jfa-rc/Luke+18:19

> Jesus lhe disse: Porque me chamas bom? Ninguém há bom, senão um, que é Deus.


### `M`: Vc acredita que tem guardado os 10 `MANDAMENTOS`?

Pergunta:

Provavelmente a pessoa respondeu que sim se considera uma boa pessoa, então essa
fase consiste em levá-la sistematicamente pelos mandamentos. Para isso
perguntamos: `ja que vc e uma boa pessoa se importa se verificamos isso juntos
com alguns dos mandamentos?`.

Não precisa ser todos os mandamentos, por exemplo os seguintes:

* Mandamento 9: Alguma vez mentiu?

A pessoa vai responder que sim, então perguntamos `em que isso te converte?`
Talvez a pessoa não saiba responder e fique meio dando voltas, se for o caso dai
perguntamos: `se eu minto pra vc, eu sou um?`. Buscamos que a pessoa responda
`mentiroso`.

* Mandamento 8: Alguma vez vc roubou alguma coisa?

Da mesma forma a pessoa vai responder que sim, então perguntamos `em que isso te
converte?` Buscamos que a pessoa responda `ladrão`.

* Mandamento 10: Alguma vez sentiu luxuria por alguém?

Aqui explicamos diretamente `isso te converte em um adultero no coração aos
olhos de Deus`, pois Jesus falou em [Mateus 5:28][pt-matthew-5:28]:
[pt-matthew-5:28]: bible://jfa-rc/Matthew+5:28

> Eu, porém, vos digo, que qualquer que atentar numa mulher para a cobiçar, já
> em seu coração cometeu adultério com ela.

* Mandamento 6: Alguma vez tem odiado alguém?

Aqui explicamos diretamente `isso te converte em um homicida aos olhos de Deus`, pois
como esta escrito em [1 João 3:15][pt-john-3:15]:
[pt-john-3:15]: bible://jfa-rc/John+3:15

> Qualquer que aborrece a seu irmão é homicida. E vós sabeis que nenhum homicida
> tem permanecente nele a vida eterna.

* Mandamento 3: Alguma vez usou o nome de Deus em vão?

Aqui explicamos diretamente `isso te converte em um blasfemo`.


Finalmente `sumarizamos` para apessoa da seguinte forma: `bom [nome da pessoa],
segum como vc mesmo reconheceu pelas suas proprias admicoes, vc e um mentiroso,
ladrao, adultero no coracao e homicida. E esses sao apenas 4 dos 10
mandamentos`. Daqui passamos para a próxima seção (pergunta).

Versículos de referencia:

  * Primeiro: Não terás outros deuses diante de mim (Ex 20:3 e Dt 5:7)
  * Segundo: Não farás para ti Ídolo (Ex 20:4-6 e Dt 5:8-10)
  * Terceiro: Não tomarás o nome do SENHOR teu Deus em vão (Ex 20:7 e Dt 5:11)
  * Quarto: Lembra-te do dia do sábado, para o santificar (Ex 20:8-11 e Dt 5:12-15)
  * Quinto: Honra a teu pai e a tua mãe (Ex 20:12 e Dt 5:16)
  * Sexto: Não matarás (Ex 20:13 e Dt 5:17)
  * Sétimo: Não adulterarás (Ex 20:14 e Dt 5:18)
  * Oitavo: Não furtarás (Ex 20:15 e Dt 5:19)
  * Noveno: Não dirás falso testemunho contra o teu próximo (Ex 20:16 e Dt 5:20)
  * Decimo: Não cobiçarás (Ex 20:17 e Dt 5:21)


### `J`: Se Deus te `JULGASSE` pelos 10 mandamentos, vc seria inocente ou culpável?

Pergunta:

Uma vez que a pessoa esta consciente dos seus pecados agora perguntamos: `Se
Deus te JULGASSE pelos 10 mandamentos, vc seria inocente ou culpavel?`, se a
pessoa responder culpável passamos para a próxima seção (pergunta).

Se a pessoa responder que ainda e inocente porque e uma boa pessoa ou que Deus e bom
e não vai julgar desse jeito, então respondemos: `essa e uma violacao do segundo
mandamento, pois vc esta crieo um Deus falso com o qual vc se sente falsamente
protegido, isso se chama idolatria. E um pecado e eu tambem ja fiz isso antes de
tomar consciencia dessas coisas que estou te faleo`.

E continuamos dizendo: `faz sentido que Deus permita entrar nos Ceus a
mentirosos, ladrões, adulteros, assasinos e blasfemos?`

Analogia:

E agora fazemos uma analogia com o sistema judicial da terra se for necessário:
`Se vc comete um crime e rouba um carro e vai no julgamento, e dai fala para o
juiz: tudo bem eu errei mas me arrependo pq eu sou bomzinho`. Acha que o juiz
vai falar: tudo bem, isso e o que eu queria ouvir, pode ir embora tranquilo não
tem problema? `Se o juiz e um juiz justo, quanto mais Deus e um Deus justo, e
por isso ele vai fazer justica.`

Versículo de referencia: [Romanos 10:9][pt-romans-10:9-10]-10:
[pt-romans-10:9-10]: bible://jfa-rc/Romans+10:9

> Porque todos pecaram e destituídos estão da glória de Deus.

### `D`: O seu `DESTINO` seria os Céus ou o inferno?

Pergunta:

Agora perguntamos: `isso não preocupa vc, onde vc vai passar a eternidade?
Porque isso me preocupa, e por isso estou aqui faleo com vc, porque vc tem um
alma que me importa e não quero que vc se perca ou seja condenado e va para o
inferno, e quero que vc vá pro Céu`

Explicação:

Sabemos que os 10 mandamentos são certos, e obvio que esta errado mentir,
roubar, adulterar e assassinar. Deus nos deu consciência e por isso Ele vai
julgar a humanidade. Se Deus for bom e justo, ele vai julgar os assassinos,
mentirosos, ladrões e adúlteros e vc admitiu que vc e um desses.

Vc esta num problema serio, e a Bíblia fala claramente que vc iria para o
inferno e isso deveria `preocupar seriamente` vc. Vc não gostaria de perder a
sua vida, certo?

Nesse ponto devemos `observar o jeito de falar` da pessoa, se continua mesmo
assim se justificando ou não. Se admite os seus erros então esta pronta para
receber o evangelho.

Devemos ser sinceros e falar: `não estou te mentindo, eu não estou aqui pelo seu
dinheiro ou para que vc venha na minha igreja. Eu só quero ser sincero com vc.
Por favor leva a serio e reflete ao respeito da sua salvação, imagine vc no dia
de julgamento`.

Agora passamos para a segunda parte do método, o `Evangelho`.

Versículo de referencia: [Mateus 18:9][pt-matthew-18:9]
[pt-matthew-18:9]: bible://jfa-rc/Matthew+18:9

> E se o teu olho te escandalizar, arranca-o, e atira-o para longe de ti. Melhor
> te é entrar na vida com um só olho, do que, tendo dois olhos, seres lançado no
> fogo do inferno.


### Evangelho: A BOA noticia (`PCAFB`)

A segunda parte consiste em perguntar se a pecado/condenação preocupa ele. Essa
e a grande pergunta, seja sim ou não a resposta damos a boa noticia do
Evangelho.


#### `P`: Isso `Preocupa` vc?

Pergunta: Apos a pessoa responder que iria para o `inferno` perguntamos simplesmente:
`Isso preocupa vc? Isso e aterrador porque se algo acontecesse com vc hoje, vc
nao teria desculpa porque Deus te deu uma consciencia e vc sabe distinguir o que
e certo do que e errado. E ir para o inferno e algo terrivel para qualquer
pessoa`.

Analogia: `analogia dos olhos` para esclarecer o `valor da alma`.  Se alguém
vem para vc e fala que quer comprar um dos seus olhos por 500.000 reais, e tem
um tratamento medico que vc nem vai perceber a diferença porque vai ser
implantado um olho de cristal, só que não vai enxergar por um olho. Vc não vai
sentir dor, só vai perder um dos seus olhos. Vc aceitaria? E se fossem os dois
olhos por 1.000.000 de reais? Provavelmente a pessoa vai falar que não.

Explicação: dai então falamos: `assim como os teus
olhos sao mais valiosos para vc do que o dinheiro, quanto mais a tua alma`.

Versículos de referencia: Esta escrito que Jesus disse em [Mateus
18:9][pt-matthew-18:9] e em [Mateus 5:29][pt-matthew-5:29]:
[pt-matthew-5:29]: bible://jfa-rc/Matthew+5:29

> Portanto, se o teu olho direito te escandalizar, arranca-o e atira-o para
> longe de ti, pois te é melhor que se perca um dos teus membros do que seja
> todo o teu corpo lançado no inferno.


#### `C`: Leve-o para a `Cruz`

Analogia: `analogia do pagador da fiança`. Imagina que vc e culpável de um crime
e vc esta no julgamento e falam que a sua fiança para ser livre são 100.000
reais e vc não tem esse dinheiro. Do nada aparece alguém e fala, eu vou pagar
por ele. O que vc sentiria por essa pessoa?

Explicação: `Isso foi o que Jesus fez ha 2000 anos atras quando veio no mundo e
morreu na cruz para pagar os nossos pecados com a Sua morte`.

Versículos de referencia: Esta escrito em [João 3:16][pt-john-3:16]-17:
[pt-john-3:16]: bible://jfa-rc/John+3:16

> Porque Deus amou o Mundo de tal maneira que deu o seu Filho unigénito, para
> que todo aquele que nele crê não pereça, mas tenha a vida eterna. Porque Deus
> enviou o seu Filho ao mundo, não para que condenasse o mundo, mas para que o
> mundo fosse salvo por ele.


#### `AF`: `Arrependimento` e `Fé`

Analogia: `paraquedas`. Se vc se lança de um avião vc precisa um paraquedas,
porque a lei da gravidade vai matar vc, certo? Da mesma forma a lei do pecado
vai matar vc e vc precisa de duas coisas `arrependimendo e fé`

Explicação: Deus quer dar uma oportunidade para nos todos e limpar-nos dos
nossos pecados, mas para isso devemos humilharmos diante dele e reconhecer que
somos pecadores e que não podemos entrar no Céu pelas nossas obras mas que
precisamos de Jesus.

E importante que vc se arrependa com coração sincero e confesse seus pecados a
Deus, como esta escrito em [1
João 1:9][pt-1john-1:9]:
[pt-1john-1:9]: bible://jfa-rc/1John+1:9

> Se confessarmos os nossos pecados, ele é fiel e justo, para nos perdoar os
> pecados, e nos purificar de toda a injustiça.

Mas também devemos nos desviar desses pecados e não cometê-los mais. Isto e o
verdadeiro arrependimento quando vc para de cometer esses pecados, como esta
escrito em:
[Ezequiel 18:21][pt-ezequiel-18:21-23]-23:
[pt-ezequiel-18:21-23]: bible://jfa-rc/Ezequiel+18:21

> Mas, se o ímpio se converter de todos os seus pecados que cometeu, e guardar
> todos os meus estatutos, e fizer juízo e justiça, certamente viverá; não
> morrerá. De todas as suas transgressões que cometeu não haverá lembrança
> contra ele; pela sua justiça que praticou, viverá. Desejaria eu, de qualquer
> maneira, a morte do ímpio? Diz o Senhor JEOVÁ; não desejo, antes, que se
> converta dos seus caminhos e viva?

Também e importante que vc tenha fé e acredite que se vc busca a misericórdia de
Deus a traves de Jesus Cristo, vc pode alcançá-la como esta escrito em:
[Romanos 10:9][pt-romans-10:9-10]-10:
[pt-romans-10:9-10]: bible://jfa-rc/Romans+10:9

> A saber: Se com a tua boca confessares ao SENHOR Jesus, e, em teu coração
> creres que Deus o ressuscitou dos mortos, serás salvo. Visto que com o coração
> se crê para a justiça, e com a boca se faz confissão para a salvação.

Vc não pode só acreditar que o paraquedas vai te salvar, vc tem que usar o
paraquedas.


#### `B`: Leia a `Biblia`

Leia a Bíblia todos os dias, mesmo que for um trechinho pequeno, Ela vai te
ajudar nos momento de dificuldade. Obedeça o que vc esta lendo.

Vc tem uma Bíblia para ler?

<!--  vim: set spell: -->
<!--  vim: set spelllang=pt: -->
